// const NEUTRAL_EVENTS = [
//     'Pulling',
//     'ScalingReplicaSet',
//     'Pulled',
//     'NodeHasSufficientMemory',
//     'SandboxChanged',
//     'UPDATE',
//     'CREATE',
//     'NodeHasNoDiskPressure',
//     'RecreatingFailedPod',
//     'NodeHasSufficientDisk',
//     'Starting',
//     'UpdatedLoadBalancer',
//     'NodeHasSufficientPID',
//     'NodeAllocatableEnforced',
//     'Rebooted',
//     'LeaderElection',
//     'Preempted',
//     'KeyPairVerified',
// ];

export const POSITIVE_EVENTS = [
    'SuccessfulDelete',
    'Created',
    'Scheduled',
    'Started',
    'SuccessfulCreate',
    'SawCompletedJob',
    'SuccessfulAttachVolume',
    'NodeReady',
]

export const NEGATIVE_EVENTS = [
    'FailedScheduling',
    'UnregisterNetDevice',
    'Unhealthy',
    'Killing',
    'FailedGetScale',
    'NodeHasInsufficientMemory',
    'BackOff',
    'FailedDaemonPod',
    'Failed',
    'EvictionThresholdMet',
    'BackoffLimitExceeded',
    'FailedGetResourceMetric',
    'ErrImageNeverPull',
    'ImageGCFailed',
    'TooManyActivePods',
    'FailedComputeMetricsReplicas',
    'ExceededGracePeriod',
    'NetworkNotReady',
    'FreeDiskSpaceFailed',
    'SystemOOM',
    'NodeNotReady',
    'FailedToUpdateEndpoint',
    'OOMKilling',
    'CIDRAssignmentFailed',
    'FailedCreate',
    'FailedRescale',
    'FailedMount',
    'FailedKillPod',
    'ERROR',
    'FailedCreatePodSandBox',
    'DeadlineExceeded',
    'KiamCredentialError',
    'FailedSync'
];